"""
Analytics Commands for MG-CLI

Manages analytics setup, data collection, and reporting for MG Games.
Integrates with Firebase Analytics, BigQuery, and marketing attribution.
"""

import click
import json
from pathlib import Path
from typing import Optional, Dict, List, Any
from datetime import datetime, timedelta


class AnalyticsConfig:
    """Analytics configuration for a game"""

    # Standard events for mobile games
    STANDARD_EVENTS = {
        # Engagement events
        "session_start": {"params": ["session_id", "platform"]},
        "session_end": {"params": ["session_id", "duration_seconds"]},
        "level_start": {"params": ["level_id", "level_name"]},
        "level_end": {"params": ["level_id", "success", "score", "duration"]},

        # Monetization events
        "ad_impression": {"params": ["ad_type", "ad_unit", "placement", "revenue"]},
        "ad_click": {"params": ["ad_type", "ad_unit", "placement"]},
        "purchase": {"params": ["product_id", "price", "currency", "quantity"]},
        "subscription": {"params": ["product_id", "period", "price", "currency"]},

        # Retention events
        "tutorial_begin": {"params": []},
        "tutorial_complete": {"params": ["duration_seconds"]},
        "first_purchase": {"params": ["product_id", "price", "currency"]},

        # Custom game events
        "unlock_achievement": {"params": ["achievement_id", "achievement_name"]},
        "spend_virtual_currency": {"params": ["item_name", "virtual_currency_name", "value"]},
        "earn_virtual_currency": {"params": ["virtual_currency_name", "value", "source"]},
    }

    # Marketing attribution sources
    ATTRIBUTION_SOURCES = [
        "organic",
        "google_ads",
        "facebook_ads",
        "unity_ads",
        "applovin",
        "ironsource",
        "tiktok_ads",
        "apple_search_ads",
        "cross_promo",
        "influencer",
    ]

    # Key performance indicators
    KPIS = {
        "dau": "Daily Active Users",
        "mau": "Monthly Active Users",
        "retention_d1": "Day 1 Retention",
        "retention_d7": "Day 7 Retention",
        "retention_d30": "Day 30 Retention",
        "arpu": "Average Revenue Per User",
        "arppu": "Average Revenue Per Paying User",
        "ltv": "Lifetime Value",
        "cpi": "Cost Per Install",
        "roas": "Return on Ad Spend",
        "session_length": "Average Session Length",
        "sessions_per_day": "Sessions Per Day Per User",
        "ad_revenue_per_dau": "Ad Revenue per DAU",
        "iap_revenue_per_dau": "IAP Revenue per DAU",
    }


class AnalyticsService:
    """Analytics management service"""

    def __init__(self):
        self.config = AnalyticsConfig()

    def generate_events_schema(self, game_id: str) -> Dict[str, Any]:
        """Generate analytics events schema for a game"""
        return {
            "game_id": game_id,
            "version": "1.0.0",
            "generated_at": datetime.now().isoformat(),
            "events": self.config.STANDARD_EVENTS,
            "user_properties": {
                "first_open_time": "timestamp",
                "first_purchase_time": "timestamp",
                "total_spend": "number",
                "player_level": "number",
                "vip_level": "number",
                "attribution_source": "string",
                "campaign_id": "string",
            },
        }

    def generate_bigquery_schema(self, game_id: str) -> str:
        """Generate BigQuery table schema for analytics"""
        schema = """
-- BigQuery Schema for {game_id}
-- Generated by MG-CLI

-- Events table
CREATE TABLE IF NOT EXISTS `{project_id}.analytics_{game_id}.events` (
  event_date DATE,
  event_timestamp TIMESTAMP,
  event_name STRING,
  event_params ARRAY<STRUCT<key STRING, value STRUCT<string_value STRING, int_value INT64, float_value FLOAT64>>>,
  user_id STRING,
  user_pseudo_id STRING,
  platform STRING,
  app_version STRING,
  geo STRUCT<country STRING, region STRING, city STRING>,
  device STRUCT<category STRING, mobile_brand_name STRING, mobile_model_name STRING, operating_system STRING, operating_system_version STRING>,
  traffic_source STRUCT<source STRING, medium STRING, campaign STRING>
)
PARTITION BY event_date
CLUSTER BY event_name, user_pseudo_id;

-- User properties table
CREATE TABLE IF NOT EXISTS `{project_id}.analytics_{game_id}.user_properties` (
  user_id STRING,
  user_pseudo_id STRING,
  first_open_time TIMESTAMP,
  first_purchase_time TIMESTAMP,
  total_spend FLOAT64,
  player_level INT64,
  vip_level INT64,
  attribution_source STRING,
  campaign_id STRING,
  last_active_date DATE
)
CLUSTER BY user_pseudo_id;

-- Daily metrics view
CREATE OR REPLACE VIEW `{project_id}.analytics_{game_id}.daily_metrics` AS
SELECT
  event_date,
  COUNT(DISTINCT user_pseudo_id) as dau,
  COUNT(*) as total_events,
  SUM(CASE WHEN event_name = 'ad_impression' THEN 1 ELSE 0 END) as ad_impressions,
  SUM(CASE WHEN event_name = 'purchase' THEN 1 ELSE 0 END) as purchases
FROM `{project_id}.analytics_{game_id}.events`
GROUP BY event_date;
""".format(game_id=game_id, project_id="mg-games-analytics")

        return schema

    def generate_dashboard_config(self, game_id: str) -> Dict[str, Any]:
        """Generate Looker/Data Studio dashboard configuration"""
        return {
            "game_id": game_id,
            "dashboards": [
                {
                    "name": "Overview",
                    "charts": [
                        {"type": "timeseries", "metric": "dau", "title": "Daily Active Users"},
                        {"type": "timeseries", "metric": "revenue", "title": "Revenue"},
                        {"type": "retention_curve", "title": "Retention"},
                        {"type": "pie", "dimension": "attribution_source", "title": "User Acquisition"},
                    ],
                },
                {
                    "name": "Monetization",
                    "charts": [
                        {"type": "timeseries", "metric": "ad_revenue", "title": "Ad Revenue"},
                        {"type": "timeseries", "metric": "iap_revenue", "title": "IAP Revenue"},
                        {"type": "bar", "metric": "arpu", "dimension": "cohort_week", "title": "ARPU by Cohort"},
                        {"type": "funnel", "title": "Purchase Funnel"},
                    ],
                },
                {
                    "name": "Marketing",
                    "charts": [
                        {"type": "table", "dimension": "campaign", "metrics": ["installs", "cpi", "roas"], "title": "Campaign Performance"},
                        {"type": "timeseries", "metric": "installs", "dimension": "source", "title": "Installs by Source"},
                        {"type": "scatter", "x": "spend", "y": "revenue", "title": "Spend vs Revenue"},
                    ],
                },
            ],
        }


class MarketingService:
    """Marketing campaign management service"""

    # Major marketing channels
    CHANNELS = {
        "google_ads": {
            "name": "Google Ads (UAC)",
            "platforms": ["android", "ios"],
            "campaign_types": ["app_installs", "app_engagement", "app_pre_registration"],
            "bidding_strategies": ["target_cpa", "target_roas", "maximize_conversions"],
        },
        "facebook_ads": {
            "name": "Meta Ads (Facebook/Instagram)",
            "platforms": ["android", "ios"],
            "campaign_types": ["app_installs", "app_events", "value_optimization"],
            "bidding_strategies": ["lowest_cost", "cost_cap", "bid_cap"],
        },
        "apple_search_ads": {
            "name": "Apple Search Ads",
            "platforms": ["ios"],
            "campaign_types": ["basic", "advanced"],
            "bidding_strategies": ["cpt_max", "cpa_goal"],
        },
        "unity_ads": {
            "name": "Unity Ads",
            "platforms": ["android", "ios"],
            "campaign_types": ["cpi", "cpe", "roas"],
            "bidding_strategies": ["auto", "manual"],
        },
        "applovin": {
            "name": "AppLovin",
            "platforms": ["android", "ios"],
            "campaign_types": ["max_cpi", "max_roas"],
            "bidding_strategies": ["auto", "target_roas"],
        },
        "ironsource": {
            "name": "ironSource",
            "platforms": ["android", "ios"],
            "campaign_types": ["cpi", "cpe", "roas"],
            "bidding_strategies": ["auto", "manual"],
        },
        "tiktok_ads": {
            "name": "TikTok Ads",
            "platforms": ["android", "ios"],
            "campaign_types": ["app_installs", "conversions"],
            "bidding_strategies": ["lowest_cost", "cost_cap"],
        },
    }

    # Campaign templates
    CAMPAIGN_TEMPLATES = {
        "soft_launch": {
            "budget_daily": 100,
            "duration_days": 14,
            "geo_targets": ["PH", "TH", "VN"],  # Tier 3 test markets
            "goal": "product_validation",
            "kpis": ["d1_retention", "session_length", "crash_rate"],
        },
        "global_launch": {
            "budget_daily": 5000,
            "duration_days": 30,
            "geo_targets": ["US", "GB", "CA", "AU", "DE", "FR", "JP", "KR"],
            "goal": "scale_acquisition",
            "kpis": ["cpi", "roas_d7", "installs"],
        },
        "retention_focused": {
            "budget_daily": 1000,
            "duration_days": 7,
            "geo_targets": ["US", "JP", "KR"],
            "goal": "high_quality_users",
            "kpis": ["d7_retention", "ltv_d30", "arppu"],
        },
        "monetization_test": {
            "budget_daily": 500,
            "duration_days": 14,
            "geo_targets": ["US", "GB", "DE"],
            "goal": "revenue_optimization",
            "kpis": ["arpu", "iap_conversion", "ad_ecpm"],
        },
    }

    def generate_campaign_plan(
        self,
        game_id: str,
        template: str,
        channels: List[str],
    ) -> Dict[str, Any]:
        """Generate marketing campaign plan"""
        if template not in self.CAMPAIGN_TEMPLATES:
            return {"error": f"Unknown template: {template}"}

        tpl = self.CAMPAIGN_TEMPLATES[template]

        plan = {
            "game_id": game_id,
            "template": template,
            "created_at": datetime.now().isoformat(),
            "budget": {
                "daily": tpl["budget_daily"],
                "total": tpl["budget_daily"] * tpl["duration_days"],
                "duration_days": tpl["duration_days"],
            },
            "geo_targets": tpl["geo_targets"],
            "goal": tpl["goal"],
            "kpis": tpl["kpis"],
            "channels": [],
        }

        for channel in channels:
            if channel in self.CHANNELS:
                ch = self.CHANNELS[channel]
                plan["channels"].append({
                    "id": channel,
                    "name": ch["name"],
                    "platforms": ch["platforms"],
                    "recommended_campaign_type": ch["campaign_types"][0],
                    "recommended_bidding": ch["bidding_strategies"][0],
                    "budget_allocation": tpl["budget_daily"] / len(channels),
                })

        return plan

    def generate_attribution_config(self, game_id: str) -> Dict[str, Any]:
        """Generate attribution/MMP configuration"""
        return {
            "game_id": game_id,
            "mmp": "adjust",  # or "appsflyer", "singular", "branch"
            "attribution_window": {
                "click": 7,  # days
                "impression": 1,  # day
            },
            "reattribution_window": 90,  # days
            "postbacks": [
                {"event": "install", "partners": ["all"]},
                {"event": "purchase", "partners": ["all"], "send_revenue": True},
                {"event": "ad_revenue", "partners": ["all"], "send_revenue": True},
                {"event": "level_complete", "partners": ["google_ads", "facebook_ads"]},
            ],
            "deep_linking": {
                "enabled": True,
                "scheme": f"mggame{game_id}",
                "domain": f"link.monthlygames.com/{game_id}",
            },
            "fraud_prevention": {
                "enabled": True,
                "rules": [
                    "click_injection_protection",
                    "install_validation",
                    "anomaly_detection",
                ],
            },
        }


# Click commands
@click.group("analytics")
def analytics():
    """Analytics and marketing commands"""
    pass


@analytics.command("setup")
@click.option("--game", "-g", required=True, help="Game ID")
@click.option("--output", "-o", type=click.Path(), help="Output directory")
@click.pass_context
def setup_analytics(ctx, game, output):
    """Generate analytics configuration files"""
    service = AnalyticsService()

    output_dir = Path(output) if output else Path(f"./analytics_{game}")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Events schema
    events = service.generate_events_schema(game)
    with open(output_dir / "events_schema.json", "w") as f:
        json.dump(events, f, indent=2)
    click.echo(f"  Created: events_schema.json")

    # BigQuery schema
    bq_schema = service.generate_bigquery_schema(game)
    with open(output_dir / "bigquery_schema.sql", "w") as f:
        f.write(bq_schema)
    click.echo(f"  Created: bigquery_schema.sql")

    # Dashboard config
    dashboard = service.generate_dashboard_config(game)
    with open(output_dir / "dashboard_config.json", "w") as f:
        json.dump(dashboard, f, indent=2)
    click.echo(f"  Created: dashboard_config.json")

    click.echo(f"\nAnalytics config generated at: {output_dir}")


@analytics.command("kpis")
def list_kpis():
    """List standard game KPIs"""
    config = AnalyticsConfig()

    click.echo("\nStandard Game KPIs:")
    click.echo("=" * 50)
    for key, desc in config.KPIS.items():
        click.echo(f"  {key:25} {desc}")


@analytics.command("events")
def list_events():
    """List standard analytics events"""
    config = AnalyticsConfig()

    click.echo("\nStandard Analytics Events:")
    click.echo("=" * 50)
    for event, spec in config.STANDARD_EVENTS.items():
        params = ", ".join(spec["params"]) if spec["params"] else "(none)"
        click.echo(f"  {event:30} params: {params}")


@click.group("marketing")
def marketing():
    """Marketing campaign commands"""
    pass


@marketing.command("channels")
def list_channels():
    """List supported marketing channels"""
    service = MarketingService()

    click.echo("\nSupported Marketing Channels:")
    click.echo("=" * 60)
    for key, ch in service.CHANNELS.items():
        platforms = ", ".join(ch["platforms"])
        click.echo(f"  {key:20} {ch['name']:30} [{platforms}]")


@marketing.command("plan")
@click.option("--game", "-g", required=True, help="Game ID")
@click.option("--template", "-t",
              type=click.Choice(["soft_launch", "global_launch", "retention_focused", "monetization_test"]),
              default="soft_launch", help="Campaign template")
@click.option("--channels", "-c", multiple=True,
              default=["google_ads", "facebook_ads"],
              help="Marketing channels to use")
@click.option("--output", "-o", type=click.Path(), help="Output file")
@click.pass_context
def create_plan(ctx, game, template, channels, output):
    """Create marketing campaign plan"""
    service = MarketingService()

    plan = service.generate_campaign_plan(game, template, list(channels))

    if output:
        with open(output, "w") as f:
            json.dump(plan, f, indent=2)
        click.echo(f"Campaign plan saved to: {output}")
    else:
        click.echo("\nCampaign Plan:")
        click.echo("=" * 60)
        click.echo(f"Game: {plan['game_id']}")
        click.echo(f"Template: {plan['template']}")
        click.echo(f"Goal: {plan['goal']}")
        click.echo(f"\nBudget:")
        click.echo(f"  Daily: ${plan['budget']['daily']}")
        click.echo(f"  Total: ${plan['budget']['total']} ({plan['budget']['duration_days']} days)")
        click.echo(f"\nGeo Targets: {', '.join(plan['geo_targets'])}")
        click.echo(f"KPIs: {', '.join(plan['kpis'])}")
        click.echo(f"\nChannels:")
        for ch in plan["channels"]:
            click.echo(f"  - {ch['name']}: ${ch['budget_allocation']}/day")


@marketing.command("attribution")
@click.option("--game", "-g", required=True, help="Game ID")
@click.option("--output", "-o", type=click.Path(), help="Output file")
@click.pass_context
def attribution_config(ctx, game, output):
    """Generate MMP/attribution configuration"""
    service = MarketingService()

    config = service.generate_attribution_config(game)

    if output:
        with open(output, "w") as f:
            json.dump(config, f, indent=2)
        click.echo(f"Attribution config saved to: {output}")
    else:
        click.echo(json.dumps(config, indent=2))
