"""
Infrastructure Commands for MG-CLI

Manages cloud infrastructure setup for MG Games.
Supports GCP, AWS, and Firebase infrastructure.
"""

import click
import json
from pathlib import Path
from typing import Dict, Any, List
from datetime import datetime


class InfraConfig:
    """Infrastructure configuration templates"""

    # GCP project structure for game services
    GCP_SERVICES = {
        "firebase": {
            "products": ["analytics", "crashlytics", "remote_config", "cloud_messaging", "app_check"],
            "required": True,
        },
        "cloud_run": {
            "services": ["game-api", "admin-api", "webhook-handler"],
            "required": False,
        },
        "cloud_functions": {
            "functions": ["on_purchase", "on_user_signup", "daily_rewards", "leaderboard_update"],
            "required": False,
        },
        "bigquery": {
            "datasets": ["analytics", "events", "user_data"],
            "required": True,
        },
        "cloud_storage": {
            "buckets": ["assets", "user_uploads", "backups"],
            "required": True,
        },
        "pubsub": {
            "topics": ["game_events", "purchase_events", "analytics_events"],
            "required": False,
        },
    }

    # Environment tiers
    ENVIRONMENTS = {
        "dev": {
            "suffix": "-dev",
            "tier": "free",
            "scaling": {"min": 0, "max": 1},
        },
        "staging": {
            "suffix": "-stg",
            "tier": "standard",
            "scaling": {"min": 1, "max": 3},
        },
        "prod": {
            "suffix": "",
            "tier": "production",
            "scaling": {"min": 2, "max": 10},
        },
    }

    # Cost estimation (monthly, USD)
    COST_ESTIMATES = {
        "firebase_free": 0,
        "firebase_blaze_base": 25,  # Blaze plan base
        "bigquery_1tb": 5,
        "cloud_run_basic": 50,
        "cloud_storage_100gb": 2.3,
        "cloud_functions_1m": 0.40,
    }


class InfraService:
    """Infrastructure management service"""

    def __init__(self):
        self.config = InfraConfig()

    def generate_terraform_config(
        self, game_id: str, env: str, services: List[str]
    ) -> str:
        """Generate Terraform configuration"""
        env_config = self.config.ENVIRONMENTS.get(env, self.config.ENVIRONMENTS["dev"])
        project_id = f"mg-game-{game_id}{env_config['suffix']}"

        tf_config = f'''# Terraform configuration for {project_id}
# Generated by MG-CLI at {datetime.now().isoformat()}

terraform {{
  required_providers {{
    google = {{
      source  = "hashicorp/google"
      version = "~> 5.0"
    }}
  }}
}}

provider "google" {{
  project = "{project_id}"
  region  = "asia-northeast3"  # Seoul
}}

# Firebase project
resource "google_firebase_project" "default" {{
  provider = google-beta
  project  = "{project_id}"
}}

# Firebase Android app
resource "google_firebase_android_app" "default" {{
  provider     = google-beta
  project      = "{project_id}"
  display_name = "MG Game {game_id} ({env})"
  package_name = "com.monthlygames.game{game_id}"
  depends_on   = [google_firebase_project.default]
}}

# Firebase iOS app
resource "google_firebase_ios_app" "default" {{
  provider     = google-beta
  project      = "{project_id}"
  display_name = "MG Game {game_id} ({env})"
  bundle_id    = "com.monthlygames.game{game_id}"
  depends_on   = [google_firebase_project.default]
}}
'''

        # Add BigQuery dataset if requested
        if "bigquery" in services:
            tf_config += f'''
# BigQuery dataset for analytics
resource "google_bigquery_dataset" "analytics" {{
  dataset_id = "analytics_{game_id}"
  project    = "{project_id}"
  location   = "asia-northeast3"

  labels = {{
    env     = "{env}"
    game_id = "{game_id}"
  }}
}}
'''

        # Add Cloud Storage if requested
        if "cloud_storage" in services:
            tf_config += f'''
# Cloud Storage buckets
resource "google_storage_bucket" "assets" {{
  name     = "{project_id}-assets"
  project  = "{project_id}"
  location = "ASIA"

  uniform_bucket_level_access = true

  lifecycle_rule {{
    action {{
      type = "Delete"
    }}
    condition {{
      age = 365
    }}
  }}
}}

resource "google_storage_bucket" "backups" {{
  name     = "{project_id}-backups"
  project  = "{project_id}"
  location = "ASIA"

  uniform_bucket_level_access = true

  lifecycle_rule {{
    action {{
      type          = "SetStorageClass"
      storage_class = "COLDLINE"
    }}
    condition {{
      age = 30
    }}
  }}
}}
'''

        # Add Cloud Run if requested
        if "cloud_run" in services:
            scaling = env_config["scaling"]
            tf_config += f'''
# Cloud Run service for game API
resource "google_cloud_run_service" "game_api" {{
  name     = "game-api"
  project  = "{project_id}"
  location = "asia-northeast3"

  template {{
    spec {{
      containers {{
        image = "gcr.io/{project_id}/game-api:latest"

        resources {{
          limits = {{
            cpu    = "1000m"
            memory = "512Mi"
          }}
        }}
      }}
    }}

    metadata {{
      annotations = {{
        "autoscaling.knative.dev/minScale" = "{scaling['min']}"
        "autoscaling.knative.dev/maxScale" = "{scaling['max']}"
      }}
    }}
  }}

  traffic {{
    percent         = 100
    latest_revision = true
  }}
}}

# Allow unauthenticated access
resource "google_cloud_run_service_iam_member" "game_api_public" {{
  project  = "{project_id}"
  location = google_cloud_run_service.game_api.location
  service  = google_cloud_run_service.game_api.name
  role     = "roles/run.invoker"
  member   = "allUsers"
}}
'''

        return tf_config

    def generate_github_actions(self, game_id: str) -> str:
        """Generate GitHub Actions workflow"""
        return f'''# GitHub Actions workflow for mg-game-{game_id}
# Generated by MG-CLI

name: Build and Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  FLUTTER_VERSION: "3.24.0"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{{{ env.FLUTTER_VERSION }}}}
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get
        working-directory: game

      - name: Analyze
        run: flutter analyze
        working-directory: game

  test:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{{{ env.FLUTTER_VERSION }}}}
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get
        working-directory: game

      - name: Run tests
        run: flutter test --coverage
        working-directory: game

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: game/coverage/lcov.info

  build-android:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{{{ env.FLUTTER_VERSION }}}}
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get
        working-directory: game

      - name: Build APK
        run: flutter build apk --release
        working-directory: game

      - name: Build App Bundle
        run: flutter build appbundle --release
        working-directory: game

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: |
            game/build/app/outputs/flutter-apk/app-release.apk
            game/build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{{{ env.FLUTTER_VERSION }}}}
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get
        working-directory: game

      - name: Build iOS
        run: flutter build ios --release --no-codesign
        working-directory: game

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: game/build/ios/iphoneos

  deploy-firebase:
    runs-on: ubuntu-latest
    needs: [build-android]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: android-release
          path: ./artifacts

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{{{ secrets.FIREBASE_APP_ID }}}}
          serviceCredentialsFileContent: ${{{{ secrets.FIREBASE_SERVICE_ACCOUNT }}}}
          file: ./artifacts/app-release.apk
          groups: testers
'''

    def generate_fastlane_config(self, game_id: str) -> Dict[str, str]:
        """Generate Fastlane configuration"""
        fastfile = f'''# Fastlane configuration for mg-game-{game_id}

default_platform(:android)

platform :android do
  desc "Deploy a new internal test version to Google Play"
  lane :internal do
    upload_to_play_store(
      track: 'internal',
      aab: '../game/build/app/outputs/bundle/release/app-release.aab',
      json_key: 'google-play-key.json'
    )
  end

  desc "Deploy to production"
  lane :production do
    upload_to_play_store(
      track: 'production',
      aab: '../game/build/app/outputs/bundle/release/app-release.aab',
      json_key: 'google-play-key.json',
      rollout: '0.1'  # 10% rollout
    )
  end
end

platform :ios do
  desc "Deploy to TestFlight"
  lane :beta do
    build_app(
      workspace: '../game/ios/Runner.xcworkspace',
      scheme: 'Runner',
      export_method: 'app-store'
    )
    upload_to_testflight
  end

  desc "Deploy to App Store"
  lane :release do
    build_app(
      workspace: '../game/ios/Runner.xcworkspace',
      scheme: 'Runner',
      export_method: 'app-store'
    )
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: false,
      phased_release: true
    )
  end
end
'''

        appfile = f'''# Appfile for mg-game-{game_id}

# Android
json_key_file("google-play-key.json")
package_name("com.monthlygames.game{game_id}")

# iOS
apple_id("developer@monthlygames.com")
itc_team_id("YOUR_ITC_TEAM_ID")
team_id("YOUR_TEAM_ID")
app_identifier("com.monthlygames.game{game_id}")
'''

        return {"Fastfile": fastfile, "Appfile": appfile}

    def estimate_costs(self, services: List[str], env: str) -> Dict[str, Any]:
        """Estimate monthly infrastructure costs"""
        costs = {"items": [], "total": 0}

        # Firebase is always included
        if env == "dev":
            costs["items"].append({"name": "Firebase (Spark Plan)", "cost": 0})
        else:
            costs["items"].append({"name": "Firebase (Blaze Plan)", "cost": 25})
            costs["total"] += 25

        if "bigquery" in services:
            cost = 5 if env != "prod" else 50
            costs["items"].append({"name": f"BigQuery ({env})", "cost": cost})
            costs["total"] += cost

        if "cloud_storage" in services:
            cost = 5 if env != "prod" else 30
            costs["items"].append({"name": f"Cloud Storage ({env})", "cost": cost})
            costs["total"] += cost

        if "cloud_run" in services:
            cost = 0 if env == "dev" else (50 if env == "staging" else 200)
            costs["items"].append({"name": f"Cloud Run ({env})", "cost": cost})
            costs["total"] += cost

        return costs


# Click commands
@click.group("infra")
def infra():
    """Infrastructure management commands"""
    pass


@infra.command("services")
def list_services():
    """List available infrastructure services"""
    config = InfraConfig()

    click.echo("\nAvailable Infrastructure Services:")
    click.echo("=" * 50)
    for name, spec in config.GCP_SERVICES.items():
        required = "[Required]" if spec.get("required") else "[Optional]"
        click.echo(f"\n  {name} {required}")
        if "products" in spec:
            click.echo(f"    Products: {', '.join(spec['products'])}")
        if "services" in spec:
            click.echo(f"    Services: {', '.join(spec['services'])}")
        if "datasets" in spec:
            click.echo(f"    Datasets: {', '.join(spec['datasets'])}")


@infra.command("terraform")
@click.option("--game", "-g", required=True, help="Game ID")
@click.option("--env", "-e", type=click.Choice(["dev", "staging", "prod"]),
              default="dev", help="Environment")
@click.option("--services", "-s", multiple=True,
              default=["firebase", "bigquery", "cloud_storage"],
              help="Services to include")
@click.option("--output", "-o", type=click.Path(), help="Output file")
@click.pass_context
def generate_terraform(ctx, game, env, services, output):
    """Generate Terraform configuration"""
    service = InfraService()

    tf_config = service.generate_terraform_config(game, env, list(services))

    if output:
        with open(output, "w") as f:
            f.write(tf_config)
        click.echo(f"Terraform config saved to: {output}")
    else:
        click.echo(tf_config)


@infra.command("github-actions")
@click.option("--game", "-g", required=True, help="Game ID")
@click.option("--output", "-o", type=click.Path(), help="Output file")
@click.pass_context
def generate_github_actions(ctx, game, output):
    """Generate GitHub Actions workflow"""
    service = InfraService()

    workflow = service.generate_github_actions(game)

    if output:
        with open(output, "w") as f:
            f.write(workflow)
        click.echo(f"GitHub Actions workflow saved to: {output}")
    else:
        click.echo(workflow)


@infra.command("fastlane")
@click.option("--game", "-g", required=True, help="Game ID")
@click.option("--output", "-o", type=click.Path(), help="Output directory")
@click.pass_context
def generate_fastlane(ctx, game, output):
    """Generate Fastlane configuration"""
    service = InfraService()

    configs = service.generate_fastlane_config(game)

    if output:
        output_dir = Path(output)
        output_dir.mkdir(parents=True, exist_ok=True)
        for filename, content in configs.items():
            with open(output_dir / filename, "w") as f:
                f.write(content)
            click.echo(f"Created: {output_dir / filename}")
    else:
        for filename, content in configs.items():
            click.echo(f"\n{'='*50}")
            click.echo(f"# {filename}")
            click.echo(f"{'='*50}")
            click.echo(content)


@infra.command("costs")
@click.option("--env", "-e", type=click.Choice(["dev", "staging", "prod"]),
              default="dev", help="Environment")
@click.option("--services", "-s", multiple=True,
              default=["firebase", "bigquery", "cloud_storage"],
              help="Services to estimate")
@click.pass_context
def estimate_costs(ctx, env, services):
    """Estimate monthly infrastructure costs"""
    service = InfraService()

    costs = service.estimate_costs(list(services), env)

    click.echo(f"\nMonthly Cost Estimate ({env}):")
    click.echo("=" * 40)
    for item in costs["items"]:
        click.echo(f"  {item['name']:30} ${item['cost']:>6}")
    click.echo("-" * 40)
    click.echo(f"  {'Total':30} ${costs['total']:>6}/month")
